services:
  frontend:
    build:
      context: ./TP5-DiazMarcos-Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Exponer Apache en el puerto 8080
    depends_on:
      - backend # El frontend depende del backend
#
    environment:
     - BACKEND_URL=http://localhost:4000 # Backend URL interno en la red
#


  backend:
    build:
      context: ./TP5-DiazMarcos-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Exponer el backend en el puerto 4000
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/tp5db
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
   
volumes:
  mongo-data: